# Generated by Django 4.2.2 on 2024-05-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emailValid',
        ),
        migrations.AddField(
            model_name='user',
            name='emailverify',
            field=models.CharField(default=None, max_length=6, verbose_name='email驗證狀態'),
        ),
    ]
