# Generated by Django 4.2.2 on 2024-05-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0003_alter_user_emailverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailverify',
            field=models.CharField(default='0', max_length=6, verbose_name='email驗證狀態'),
        ),
    ]
