# Generated by Django 4.2.2 on 2024-06-11 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gameApp.customize


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0004_alter_user_emailverify'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '平台評論區',
                'verbose_name_plural': '平台評論區',
                'db_table': 'CommentArea',
            },
        ),
        migrations.CreateModel(
            name='CommentAreaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='gameApp.commentarea')),
            ],
            options={
                'verbose_name': '評論研討',
                'verbose_name_plural': '評論研討',
                'db_table': 'CommentAreaAbout',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '遊戲評論區', 'verbose_name_plural': '遊戲評論區'},
        ),
        migrations.AddField(
            model_name='game',
            name='star_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='media/icon/default.png', upload_to=gameApp.customize.icon_rename, verbose_name='頭貼'),
        ),
        migrations.CreateModel(
            name='CommentAreaUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameApp.commentarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentAreaReviewUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameApp.commentareareview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commentareareview',
            name='comment_review_like',
            field=models.ManyToManyField(related_name='like_review', through='gameApp.CommentAreaReviewUserRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentareareview',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentarea',
            name='comment_like',
            field=models.ManyToManyField(related_name='like_area', through='gameApp.CommentAreaUserRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentarea',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments_area', to=settings.AUTH_USER_MODEL),
        ),
    ]
